[tool.pyright]
include = ["."]
exclude = ["**/__pycache__"]
pythonVersion = "3.10"
reportMissingImports = true
reportMissingModuleSource = true

executionEnvironments = [
  { root = ".", pythonPath = "." }
]
